Repository helaos/destiny-chip, pull requests merged in 2020-10, with the labels that each got.

#23 Modified the judgment error of the management page🍿
  destiny-chip-admin-parent/destiny-chip-admin-webui/web/WEB-INF/pages/admin/admin-page.jsp
Labels: bug

#27 add role🧈
  db/destiny_chip.sql
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/mapper/RoleMapper.java
  destiny-chip-admin-parent/destiny-chip-admin-entity/src/main/java/com/fatehole/destinychip/entity/Role.java
  destiny-chip-admin-parent/destiny-chip-admin-entity/src/main/java/com/fatehole/destinychip/entity/RoleExample.java
  destiny-chip-admin-parent/destiny-chip-admin-webui/src/main/resources/mybatis/mapper/RoleMapper.xml
  destiny-chip-common-reverse/src/main/java/com/fatehole/destinychip/entity/Role.java
  destiny-chip-common-reverse/src/main/java/com/fatehole/destinychip/entity/RoleExample.java
  destiny-chip-common-reverse/src/main/java/com/fatehole/destinychip/mapper/RoleMapper.java
  destiny-chip-common-reverse/src/main/resources/com/fatehole/destinychip/mapper/RoleMapper.xml
  destiny-chip-common-reverse/src/main/resources/generatorConfig.xml
Labels: documentation

#31 add modal🙄
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/mvc/controller/RoleController.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/service/api/RoleService.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/service/impl/RoleServiceImpl.java
  destiny-chip-admin-parent/destiny-chip-admin-webui/src/main/resources/spring-persist-mybatis.xml
  destiny-chip-admin-parent/destiny-chip-admin-webui/web/WEB-INF/pages/admin/role-page.jsp
  destiny-chip-admin-parent/destiny-chip-admin-webui/web/WEB-INF/pages/model/model-role-add.jsp
Labels: enhancement

#35 Add role delete 🎇and modify multi-select role cannot be deleted🔥
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/mvc/controller/RoleController.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/service/api/RoleService.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/service/impl/AdminServiceImpl.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/service/impl/RoleServiceImpl.java
  destiny-chip-admin-parent/destiny-chip-admin-webui/web/WEB-INF/pages/admin/role-page.jsp
  destiny-chip-admin-parent/destiny-chip-admin-webui/web/WEB-INF/pages/modal/modal-role-confirm.jsp
  destiny-chip-admin-parent/destiny-chip-admin-webui/web/static/js/my-roles.js
Labels: bug

#36 Fix small bugs🧹
  destiny-chip-admin-parent/destiny-chip-admin-webui/web/WEB-INF/pages/admin/role-page.jsp
Labels: bug

#38 Add menu maintenance data sheet🌇
  db/destiny_chip.sql
  destiny-chip-admin-parent/destiny-chip-admin-webui/web/WEB-INF/pages/admin/role-page.jsp
Labels: documentation

#49 Create an intermediate table of administrator roles🍋
  db/destiny_chip.sql
Labels: documentation

#51 Fix the bug that only save the selected character🥝
  destiny-chip-admin-parent/destiny-chip-admin-webui/web/WEB-INF/pages/admin/assign-role.jsp
Labels: bug

#52 Add permission table🎨
  db/destiny_chip.sql
Labels: documentation

#53 Add the function of assigning permissions to roles🧩
  db/destiny_chip.sql
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/mapper/AuthMapper.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/mvc/controller/AssignController.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/service/api/AuthService.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/service/impl/AuthServiceImpl.java
  destiny-chip-admin-parent/destiny-chip-admin-entity/src/main/java/com/fatehole/destinychip/entity/Auth.java
  destiny-chip-admin-parent/destiny-chip-admin-entity/src/main/java/com/fatehole/destinychip/entity/AuthExample.java
  destiny-chip-admin-parent/destiny-chip-admin-webui/src/main/resources/mybatis/mapper/AuthMapper.xml
  destiny-chip-admin-parent/destiny-chip-admin-webui/web/WEB-INF/pages/admin/role-page.jsp
  destiny-chip-admin-parent/destiny-chip-admin-webui/web/WEB-INF/pages/modal/modal-role-assign-auth.jsp
  destiny-chip-admin-parent/destiny-chip-admin-webui/web/static/js/my-roles.js
  destiny-chip-common-reverse/src/main/java/com/fatehole/destinychip/entity/Auth.java
  destiny-chip-common-reverse/src/main/java/com/fatehole/destinychip/entity/AuthExample.java
  destiny-chip-common-reverse/src/main/java/com/fatehole/destinychip/mapper/AuthMapper.java
  destiny-chip-common-reverse/src/main/resources/com/fatehole/destinychip/mapper/AuthMapper.xml
  destiny-chip-common-reverse/src/main/resources/generatorConfig.xml
Labels: enhancement

#54 Added documentation😏
  README.md
  destiny-chip-admin-parent/pom.xml
Labels: documentation

#58 Fix dependency errors🍳
  destiny-chip-admin-parent/destiny-chip-admin-component/pom.xml
  destiny-chip-admin-parent/pom.xml
Labels: bug

#61 Add spring security
  destiny-chip-admin-parent/destiny-chip-admin-component/pom.xml
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/mapper/AuthMapper.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/mvc/config/DestinyChipExceptionResolver.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/mvc/config/DestinyChipUserDetailsService.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/mvc/config/SecurityAdmin.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/mvc/config/WebAppSecurityConfig.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/mvc/controller/AdminController.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/mvc/controller/RoleController.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/service/api/AdminService.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/service/api/AuthService.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/service/impl/AdminServiceImpl.java
  destiny-chip-admin-parent/destiny-chip-admin-component/src/main/java/com/fatehole/destinychip/service/impl/AuthServiceImpl.java
  destiny-chip-admin-parent/destiny-chip-admin-webui/src/main/resources/mybatis/mapper/AuthMapper.xml
  destiny-chip-admin-parent/destiny-chip-admin-webui/src/main/resources/spring-mvc-servlet.xml
  destiny-chip-admin-parent/destiny-chip-admin-webui/src/main/resources/spring-persist-tx.xml
  destiny-chip-admin-parent/destiny-chip-admin-webui/src/main/webapp/WEB-INF/pages/admin/admin-login.jsp
  destiny-chip-admin-parent/destiny-chip-admin-webui/src/main/webapp/WEB-INF/pages/admin/admin-main.jsp
  destiny-chip-admin-parent/destiny-chip-admin-webui/src/main/webapp/WEB-INF/pages/include/nav.jsp
  destiny-chip-admin-parent/destiny-chip-admin-webui/src/main/webapp/WEB-INF/web.xml
  destiny-chip-common-util/src/main/java/com/fatehole/destinychip/constant/DestinyChipConstant.java
Labels: enhancement
